language: python

addons:
  sonarcloud:
    organization: "baimwk"
    token: 92ec8179fd85588f7eeed838c7ffa450f3ce5062

install: "pip install -r requirements.txt"

script:
  - coverage run --source=src/py_tests/ src/py_tests/test_lab4.py test
  - sonar-scanner
  
after_success:
  - coveralls
