language: python

addons:
  sonarcloud:
    organization: "baimwk"
    token: 92ec8179fd85588f7eeed838c7ffa450f3ce5062

install: "pip install -r requirements.txt"

script:
  - unittest --cov=src.py_tests/
  - sonar-scanner
  
after_success:
  - coveralls
